services:
  cognee:
    container_name: cognee
    networks:
      - cognee-network
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/cognee-frontend/ # Ignore frontend code
    environment:
      - HOST=0.0.0.0
      - ENVIRONMENT=staging
      - PYTHONPATH=.
    ports:
      - 8000:8000
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 8GB

networks:
  cognee-network:
    name: cognee-network
